"""
Text conversion API routes
"""
import io
import json
import logging
from typing import Dict, Any
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from reportlab.lib.pagesizes import A4, letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from docx import Document

from app.models.schemas import ConvertRequest

logger = logging.getLogger(__name__)
router = APIRouter()


def create_txt_file(text: str, include_metadata: bool = True) -> bytes:
    """Create plain text file"""
    content = text
    if include_metadata:
        content = f"# Generated by RAG-Anything OCR Service\n\n{text}"
    return content.encode('utf-8')


def create_md_file(text: str, filename: str = "document", include_metadata: bool = True) -> bytes:
    """Create markdown file"""
    content = f"# {filename}\n\n{text}"
    if include_metadata:
        content = f"---\ntitle: {filename}\ngenerated_by: RAG-Anything OCR Service\n---\n\n{content}"
    return content.encode('utf-8')


def create_json_file(text: str, filename: str = "document", include_metadata: bool = True) -> bytes:
    """Create JSON file"""
    data = {
        "content": text,
        "filename": filename
    }
    
    if include_metadata:
        data["metadata"] = {
            "generated_by": "RAG-Anything OCR Service",
            "word_count": len(text.split()),
            "char_count": len(text)
        }
    
    return json.dumps(data, ensure_ascii=False, indent=2).encode('utf-8')


def create_pdf_file(
    text: str, 
    filename: str = "document", 
    include_metadata: bool = True,
    page_size: str = "A4",
    font_size: int = 12
) -> bytes:
    """Create PDF file"""
    buffer = io.BytesIO()
    
    # Set page size
    if page_size.upper() == "LETTER":
        pagesize = letter
    else:
        pagesize = A4
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=pagesize,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18
    )
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=font_size + 4,
        spaceAfter=30,
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=font_size,
        leading=font_size * 1.2,
    )
    
    # Build content
    story = []
    
    # Title
    story.append(Paragraph(filename, title_style))
    story.append(Spacer(1, 12))
    
    # Metadata
    if include_metadata:
        story.append(Paragraph("Generated by RAG-Anything OCR Service", styles['Italic']))
        story.append(Spacer(1, 12))
    
    # Content
    paragraphs = text.split('\n\n')
    for paragraph in paragraphs:
        if paragraph.strip():
            story.append(Paragraph(paragraph.strip(), body_style))
            story.append(Spacer(1, 12))
    
    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def create_docx_file(text: str, filename: str = "document", include_metadata: bool = True) -> bytes:
    """Create DOCX file"""
    doc = Document()
    
    # Title
    title = doc.add_heading(filename, 0)
    
    # Metadata
    if include_metadata:
        doc.add_paragraph("Generated by RAG-Anything OCR Service").italic = True
        doc.add_paragraph("")  # Empty line
    
    # Content
    paragraphs = text.split('\n\n')
    for paragraph in paragraphs:
        if paragraph.strip():
            doc.add_paragraph(paragraph.strip())
    
    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()


@router.post("")
async def convert_text(request: ConvertRequest):
    """
    Convert text to different file formats
    
    - **text**: Text content to convert
    - **format**: Output format (txt|md|json|pdf|docx)
    - **fileName**: Output filename (without extension)
    - **includeMetadata**: Include generation metadata
    - **pdfOptions**: PDF-specific options (pageSize, fontSize)
    """
    
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="Text content cannot be empty")
    
    try:
        # Generate file content based on format
        if request.format == "txt":
            content = create_txt_file(request.text, request.includeMetadata)
            media_type = "text/plain"
            extension = "txt"
            
        elif request.format == "md":
            content = create_md_file(request.text, request.fileName, request.includeMetadata)
            media_type = "text/markdown"
            extension = "md"
            
        elif request.format == "json":
            content = create_json_file(request.text, request.fileName, request.includeMetadata)
            media_type = "application/json"
            extension = "json"
            
        elif request.format == "pdf":
            pdf_options = request.pdfOptions or {}
            content = create_pdf_file(
                request.text,
                request.fileName,
                request.includeMetadata,
                pdf_options.pageSize,
                pdf_options.fontSize
            )
            media_type = "application/pdf"
            extension = "pdf"
            
        elif request.format == "docx":
            content = create_docx_file(request.text, request.fileName, request.includeMetadata)
            media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            extension = "docx"
            
        else:
            raise HTTPException(status_code=400, detail=f"Unsupported format: {request.format}")
        
        # Create filename
        filename = f"{request.fileName}.{extension}"
        
        # Return file as streaming response
        return StreamingResponse(
            io.BytesIO(content),
            media_type=media_type,
            headers={
                "Content-Disposition": f"attachment; filename={filename}",
                "Content-Length": str(len(content))
            }
        )
        
    except Exception as e:
        logger.error(f"Error converting text to {request.format}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Conversion failed: {str(e)}")


@router.get("/formats")
async def get_supported_formats():
    """Get list of supported conversion formats"""
    return {
        "formats": [
            {
                "format": "txt",
                "name": "Plain Text",
                "description": "Simple text file with UTF-8 encoding",
                "mediaType": "text/plain"
            },
            {
                "format": "md",
                "name": "Markdown",
                "description": "Markdown formatted text with metadata",
                "mediaType": "text/markdown"
            },
            {
                "format": "json",
                "name": "JSON",
                "description": "Structured JSON with content and metadata",
                "mediaType": "application/json"
            },
            {
                "format": "pdf",
                "name": "PDF Document",
                "description": "Formatted PDF document with customizable options",
                "mediaType": "application/pdf",
                "options": {
                    "pageSize": ["A4", "Letter"],
                    "fontSize": "8-72"
                }
            },
            {
                "format": "docx",
                "name": "Word Document",
                "description": "Microsoft Word document format",
                "mediaType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            }
        ]
    }