"""Increase document processing_step length to 500

Revision ID: 29309ad81fea
Revises: 798aaed39fa5
Create Date: 2026-03-26 00:49:56.316330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29309ad81fea'
down_revision: Union[str, None] = '798aaed39fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_pattern_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('meta_pattern_id', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('patterns_executed', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('node_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meta_pattern_usage_created', 'meta_pattern_usage', ['created_at'], unique=False)
    op.create_index('idx_meta_pattern_usage_meta_pattern', 'meta_pattern_usage', ['meta_pattern_id'], unique=False)
    op.create_index(op.f('ix_meta_pattern_usage_trace_id'), 'meta_pattern_usage', ['trace_id'], unique=False)
    op.create_table('pattern_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('pattern_used', sa.String(length=100), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('edited_response', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pattern_feedback_created', 'pattern_feedback', ['created_at'], unique=False)
    op.create_index('idx_pattern_feedback_pattern', 'pattern_feedback', ['pattern_used'], unique=False)
    op.create_index('idx_pattern_feedback_type', 'pattern_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_pattern_feedback_trace_id'), 'pattern_feedback', ['trace_id'], unique=False)
    op.create_table('pattern_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('p50_latency_ms', sa.Float(), nullable=False),
    sa.Column('p95_latency_ms', sa.Float(), nullable=False),
    sa.Column('p99_latency_ms', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_name', 'query_type', 'time_window_start', name='uq_pattern_metrics_window')
    )
    op.create_index('idx_pattern_metrics_pattern', 'pattern_metrics', ['pattern_name'], unique=False)
    op.create_index('idx_pattern_metrics_time', 'pattern_metrics', ['time_window_start'], unique=False)
    op.create_table('routing_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_id', sa.String(length=100), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('old_priority', sa.Float(), nullable=False),
    sa.Column('new_priority', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('test_percentage', sa.Float(), nullable=False),
    sa.Column('test_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_id')
    )
    op.create_index('idx_routing_adjustments_pattern', 'routing_adjustments', ['pattern_name'], unique=False)
    # Removed pgvector related operations
    op.alter_column('documents', 'processing_step',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'processing_step',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index('idx_routing_adjustments_status', table_name='routing_adjustments')
    op.drop_index('idx_routing_adjustments_pattern', table_name='routing_adjustments')
    op.drop_table('routing_adjustments')
    op.drop_index('idx_pattern_metrics_time', table_name='pattern_metrics')
    op.drop_index('idx_pattern_metrics_pattern', table_name='pattern_metrics')
    op.drop_table('pattern_metrics')
    op.drop_index(op.f('ix_pattern_feedback_trace_id'), table_name='pattern_feedback')
    op.drop_index('idx_pattern_feedback_type', table_name='pattern_feedback')
    op.drop_index('idx_pattern_feedback_pattern', table_name='pattern_feedback')
    op.drop_index('idx_pattern_feedback_created', table_name='pattern_feedback')
    op.drop_table('pattern_feedback')
    op.drop_index(op.f('ix_meta_pattern_usage_trace_id'), table_name='meta_pattern_usage')
    op.drop_index('idx_meta_pattern_usage_meta_pattern', table_name='meta_pattern_usage')
    op.drop_index('idx_meta_pattern_usage_created', table_name='meta_pattern_usage')
    op.drop_table('meta_pattern_usage')
    # ### end Alembic commands ###
