"""add_chunk_metadata_fields

Revision ID: cdaba46904f0
Revises: add_temporal_fields
Create Date: 2026-01-20 18:37:44.818069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdaba46904f0'
down_revision: Union[str, None] = 'add_temporal_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_type', sa.String(length=50), nullable=True))
    op.add_column('chunks', sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('chunks', sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('chunks', sa.Column('summary', sa.String(length=500), nullable=True))
    op.add_column('chunks', sa.Column('importance_score', sa.Float(), nullable=True))
    op.alter_column('memori_conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_memori_entities_external_id'), table_name='memori_entities')
    op.drop_constraint(op.f('memori_entities_external_id_key'), 'memori_entities', type_='unique')
    op.create_index(op.f('ix_memori_entities_external_id'), 'memori_entities', ['external_id'], unique=True)
    op.alter_column('memori_entity_attributes', 'importance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'7'::double precision"))
    op.alter_column('memori_entity_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_memori_entity_attributes_attribute_key'), 'memori_entity_attributes', ['attribute_key'], unique=False)
    op.create_index(op.f('ix_memori_entity_attributes_category'), 'memori_entity_attributes', ['category'], unique=False)
    op.alter_column('memori_entity_facts', 'importance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('memori_entity_facts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_entity_preferences', 'importance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'8'::double precision"))
    op.alter_column('memori_entity_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_memori_entity_preferences_category'), 'memori_entity_preferences', ['category'], unique=False)
    op.create_index(op.f('ix_memori_entity_preferences_preference_key'), 'memori_entity_preferences', ['preference_key'], unique=False)
    op.alter_column('memori_knowledge_graph', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('memori_knowledge_graph', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_knowledge_graph', 'valid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the fact became true in reality',
               existing_nullable=True)
    op.alter_column('memori_knowledge_graph', 'invalid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the fact stopped being true in reality',
               existing_nullable=True)
    op.alter_column('memori_knowledge_graph', 'expired_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the triple was invalidated by a contradiction',
               existing_nullable=True)
    op.drop_index(op.f('idx_memori_kg_expired_at'), table_name='memori_knowledge_graph')
    op.drop_index(op.f('idx_memori_kg_valid_at'), table_name='memori_knowledge_graph')
    op.alter_column('memori_process_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_processes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_memori_processes_external_id'), table_name='memori_processes')
    op.drop_constraint(op.f('memori_processes_external_id_key'), 'memori_processes', type_='unique')
    op.create_index(op.f('ix_memori_processes_external_id'), 'memori_processes', ['external_id'], unique=True)
    op.alter_column('memori_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_memori_sessions_uuid'), table_name='memori_sessions')
    op.drop_constraint(op.f('memori_sessions_uuid_key'), 'memori_sessions', type_='unique')
    op.create_index(op.f('ix_memori_sessions_uuid'), 'memori_sessions', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memori_sessions_uuid'), table_name='memori_sessions')
    op.create_unique_constraint(op.f('memori_sessions_uuid_key'), 'memori_sessions', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_memori_sessions_uuid'), 'memori_sessions', ['uuid'], unique=False)
    op.alter_column('memori_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_memori_processes_external_id'), table_name='memori_processes')
    op.create_unique_constraint(op.f('memori_processes_external_id_key'), 'memori_processes', ['external_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_memori_processes_external_id'), 'memori_processes', ['external_id'], unique=False)
    op.alter_column('memori_processes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_process_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_memori_kg_valid_at'), 'memori_knowledge_graph', ['valid_at'], unique=False)
    op.create_index(op.f('idx_memori_kg_expired_at'), 'memori_knowledge_graph', ['expired_at'], unique=False)
    op.alter_column('memori_knowledge_graph', 'expired_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the triple was invalidated by a contradiction',
               existing_nullable=True)
    op.alter_column('memori_knowledge_graph', 'invalid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the fact stopped being true in reality',
               existing_nullable=True)
    op.alter_column('memori_knowledge_graph', 'valid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the fact became true in reality',
               existing_nullable=True)
    op.alter_column('memori_knowledge_graph', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_knowledge_graph', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_memori_entity_preferences_preference_key'), table_name='memori_entity_preferences')
    op.drop_index(op.f('ix_memori_entity_preferences_category'), table_name='memori_entity_preferences')
    op.alter_column('memori_entity_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_entity_preferences', 'importance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'8'::double precision"))
    op.alter_column('memori_entity_facts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_entity_facts', 'importance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_memori_entity_attributes_category'), table_name='memori_entity_attributes')
    op.drop_index(op.f('ix_memori_entity_attributes_attribute_key'), table_name='memori_entity_attributes')
    op.alter_column('memori_entity_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_entity_attributes', 'importance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'7'::double precision"))
    op.drop_index(op.f('ix_memori_entities_external_id'), table_name='memori_entities')
    op.create_unique_constraint(op.f('memori_entities_external_id_key'), 'memori_entities', ['external_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_memori_entities_external_id'), 'memori_entities', ['external_id'], unique=False)
    op.alter_column('memori_entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memori_conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('chunks', 'importance_score')
    op.drop_column('chunks', 'summary')
    op.drop_column('chunks', 'topics')
    op.drop_column('chunks', 'entities')
    op.drop_column('chunks', 'chunk_type')
    # ### end Alembic commands ###
