import type { BatchJob, ConvertOptions, OcrLayoutPage, OcrPage, OcrResult, OcrSettings, ProgressState } from "@/types";
import { generateId } from '@/utils/file';

// Backend API configuration
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';

// ============================================================================
// Types for new API endpoints
// ============================================================================

export interface AuthTokens {
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  expiresIn: number;
}

export interface User {
  id: string;
  email: string;
  name: string;
  role: 'admin' | 'user';
  createdAt: string;
  lastLogin?: string;
}

export interface Workspace {
  id: string;
  name: string;
  description?: string;
  ownerId: string;
  answerPolicy: 'strict' | 'balanced' | 'open';
  confidenceThreshold: number;
  createdAt: string;
  updatedAt: string;
  memberCount?: number;
}

export interface WorkspaceMember {
  userId: string;
  email: string;
  name: string;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  joinedAt: string;
}

export interface Document {
  id: string;
  workspaceId: string;
  name: string;
  originalName: string;
  mimeType: string;
  size: number;
  status: 'NEW' | 'UPLOADING' | 'INDEXING' | 'READY' | 'READY_BASIC' | 'READY_ENRICHED' | 'FAILED' | 'DELETED' | 'ARCHIVED' | 'CANCELED' | 'pending' | 'processing' | 'indexed' | 'error';
  version: number;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  indexedAt?: string;
  chunkCount?: number;
  categoryId?: string;
  // Processing progress (0-100) for background processing UI
  processingProgress?: number;
  // Current processing step description
  processingStep?: string;
  // Title from backend
  title?: string;
}

export interface DocumentVersion {
  version: number;
  createdAt: string;
  size: number;
  indexedAt?: string;
}

export interface Chunk {
  id: string;
  documentId: string;
  content: string;
  page?: number;
  section?: string;
  score?: number;
}

export interface Conversation {
  id: string;
  workspaceId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
}

export interface Message {
  id: string;
  conversationId: string;
  role: 'user' | 'assistant';
  content: string;
  citations?: Citation[];
  model?: string;
  latencyMs?: number;
  tokenUsage?: { prompt: number; completion: number };
  contextStats?: { memory_tokens: number; chunk_tokens: number; total_tokens: number };
  createdAt: string;
}

export interface Citation {
  id?: string;
  chunkId: string;
  documentId?: string;
  documentTitle?: string;  // Changed from documentName to match backend
  content?: string;
  page?: number;
  score: number;
  quote?: string;
}

export interface Category {
  id: string;
  workspaceId: string;
  name: string;
  slug: string;
  description?: string;
  contentSummary?: string;
  keywords: string[];
  icon?: string;
  color?: string;
  displayOrder: number;
  isAutoGenerated: boolean;
  documentCount: number;
}

export interface ChatQueryRequest {
  question: string;
  workspaceId?: string;
  conversationId?: string;
  model?: string;
  topK?: number;
  tags?: string[];
  documentIds?: string[];
}

export interface ChatQueryResponse {
  answer: string;
  citations: Citation[];
  model: string;
  latencyMs: number;
  evidenceScore: number;
  isGrounded: boolean;
  tokenUsage?: { prompt: number; completion: number };
  contextStats?: { memory_tokens: number; chunk_tokens: number; total_tokens: number };
  // Image generation fields
  images?: string[];  // Base64 encoded images
  isImageResponse?: boolean;
}

export interface Job {
  id: string;
  type: 'ocr' | 'index' | 'convert';
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
  progress: number;
  message?: string;
  result?: any;
  error?: string;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
}

export interface AIModel {
  id: string;
  name: string;
  provider: string;
  type: 'text' | 'image' | 'thinking';
  available: boolean;
  quota?: number;
  priority?: number;
}

export interface ProviderHealth {
  name: string;
  available: boolean;
  responseTimeMs?: number;
  quotaExceeded?: boolean;
  lastCheck?: string;
}

export interface UsageStats {
  totalRequests: number;
  totalTokens: number;
  totalCost: number;
  byProvider: Record<string, { requests: number; tokens: number; cost: number }>;
  byModel: Record<string, { requests: number; tokens: number; cost: number }>;
}

// ============================================================================
// API Client Class
// ============================================================================

class ApiClient {
  private baseUrl: string;
  private accessToken: string | null = null;
  private refreshToken: string | null = null;

  constructor(baseUrl: string = API_BASE_URL) {
    this.baseUrl = baseUrl;
    this.loadTokens();
  }

  private loadTokens() {
    this.accessToken = localStorage.getItem('accessToken');
    this.refreshToken = localStorage.getItem('refreshToken');
  }

  private saveTokens(tokens: AuthTokens) {
    this.accessToken = tokens.accessToken;
    this.refreshToken = tokens.refreshToken;
    localStorage.setItem('accessToken', tokens.accessToken);
    localStorage.setItem('refreshToken', tokens.refreshToken);
  }

  private clearTokens() {
    this.accessToken = null;
    this.refreshToken = null;
    localStorage.removeItem('accessToken');
    localStorage.removeItem('refreshToken');
  }

  public async request<T>(
    endpoint: string,
    options: RequestInit = {},
    requireAuth: boolean = false,
    timeoutMs: number = 60000 // 60 seconds default
  ): Promise<T> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...(options.headers as Record<string, string>),
    };

    if (requireAuth && this.accessToken) {
      headers['Authorization'] = `Bearer ${this.accessToken}`;
    }

    // Create abort controller for timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const response = await fetch(`${this.baseUrl}${endpoint}`, {
        ...options,
        headers,
        signal: controller.signal,
      });

      if (response.status === 401 && requireAuth) {
        // Check if this is NOT a refresh call to avoid infinite loop
        const isRefreshCall = endpoint.includes('/auth/refresh');

        if (!isRefreshCall && this.refreshToken) {
          const refreshed = await this.refreshAccessToken();
          if (refreshed) {
            headers['Authorization'] = `Bearer ${this.accessToken}`;
            const retryResponse = await fetch(`${this.baseUrl}${endpoint}`, {
              ...options,
              headers,
              signal: controller.signal,
            });
            if (!retryResponse.ok) {
              throw new Error(await this.parseError(retryResponse));
            }
            return retryResponse.json();
          }
        }

        // Emit unauthorized event for auth context to handle
        if (!isRefreshCall && typeof window !== 'undefined') {
          console.log('[API] 401 Unauthorized - emitting auth:unauthorized event');
          window.dispatchEvent(new CustomEvent('auth:unauthorized'));
        }

        // Always throw error for 401 to stop the request chain
        throw new Error('Unauthorized - please login again');
      }

      if (!response.ok) {
        throw new Error(await this.parseError(response));
      }

      // Handle 204 No Content responses (e.g., DELETE operations)
      if (response.status === 204 || response.headers.get('content-length') === '0') {
        return undefined as T;
      }

      return response.json();
    } catch (error) {
      if (error instanceof Error && error.name === 'AbortError') {
        throw new Error('Request timeout - server took too long to respond');
      }
      throw error;
    } finally {
      clearTimeout(timeoutId);
    }

  }

  private async parseError(response: Response): Promise<string> {
    try {
      const data = await response.json();
      return data.error?.message || data.detail || `HTTP ${response.status}`;
    } catch {
      return `HTTP ${response.status}`;
    }
  }

  // ==========================================================================
  // Auth Endpoints
  // ==========================================================================

  async register(email: string, password: string, name: string): Promise<User> {
    // Backend expects: { email, password, full_name }
    // Backend returns: { user: UserResponse, message: string }
    const data = await this.request<{ user: any }>(
      '/api/v1/auth/register',
      { method: 'POST', body: JSON.stringify({ email, password, full_name: name }) }
    );
    // Note: Register doesn't return tokens, user needs to login after
    return this.normalizeUser(data.user);
  }

  async login(email: string, password: string): Promise<User> {
    // Backend expects: { email, password }
    // Backend returns: { access_token, refresh_token, token_type, expires_in, user }
    const data = await this.request<{
      access_token: string;
      refresh_token: string;
      token_type: string;
      expires_in: number;
      user: any;
    }>(
      '/api/v1/auth/login',
      { method: 'POST', body: JSON.stringify({ email, password }) }
    );

    this.saveTokens({
      accessToken: data.access_token,
      refreshToken: data.refresh_token,
      tokenType: data.token_type,
      expiresIn: data.expires_in,
    });

    return this.normalizeUser(data.user);
  }

  async logout(): Promise<void> {
    try {
      await this.request('/api/v1/auth/logout', { method: 'POST' }, true);
    } finally {
      this.clearTokens();
    }
  }

  private async refreshAccessToken(): Promise<boolean> {
    try {
      const data = await this.request<{
        access_token: string;
        refresh_token: string;
        token_type: string;
        expires_in: number;
        user: any;
      }>('/api/v1/auth/refresh', {
        method: 'POST',
        body: JSON.stringify({ refresh_token: this.refreshToken }),
      });

      this.saveTokens({
        accessToken: data.access_token,
        refreshToken: data.refresh_token,
        tokenType: data.token_type,
        expiresIn: data.expires_in,
      });
      return true;
    } catch {
      this.clearTokens();
      return false;
    }
  }

  async getMe(): Promise<User> {
    const data = await this.request<any>('/api/v1/auth/me', {}, true);
    return this.normalizeUser(data);
  }

  async requestOtp(email: string, intentId: string = 'password_reset'): Promise<{ expiresLeft?: number; cooldownLeft?: number }> {
    // Backend expects: { email, intent_id }
    // Backend returns: { message, expires_in }
    const data = await this.request<{ message: string; expires_in?: number }>('/api/v1/auth/otp/request', {
      method: 'POST',
      body: JSON.stringify({ email, intent_id: intentId }),
    });
    return {
      expiresLeft: data.expires_in || 300,
      cooldownLeft: 60
    };
  }

  async verifyOtp(email: string, otp: string, intentId: string = 'password_reset'): Promise<boolean> {
    // Backend expects: { email, intent_id, otp }
    // Backend returns: { valid, message }
    const data = await this.request<{ valid: boolean; message: string }>('/api/v1/auth/otp/verify', {
      method: 'POST',
      body: JSON.stringify({ email, intent_id: intentId, otp }),
    });
    return data.valid;
  }

  async forgotPassword(email: string, otp: string, newPassword: string): Promise<void> {
    // Backend expects: { email, otp, new_password }
    await this.request('/api/v1/auth/forgot-password', {
      method: 'POST',
      body: JSON.stringify({ email, otp, new_password: newPassword }),
    });
  }

  async changePassword(currentPassword: string, newPassword: string, otp: string): Promise<void> {
    // Backend expects: { otp, current_password, new_password }
    await this.request('/api/v1/auth/change-password', {
      method: 'POST',
      body: JSON.stringify({
        otp,
        current_password: currentPassword,
        new_password: newPassword
      }),
    }, true);
  }

  isAuthenticated(): boolean {
    return !!this.accessToken;
  }

  // Helper to normalize user response from backend
  private normalizeUser(data: any): User {
    return {
      id: data.id,
      email: data.email,
      name: data.full_name || data.name || '',
      role: data.role_global || data.role || 'user',
      createdAt: data.created_at || data.createdAt,
      lastLogin: data.last_login_at || data.lastLogin,
    };
  }

  // ==========================================================================
  // Workspace Endpoints
  // ==========================================================================

  async getWorkspaces(): Promise<Workspace[]> {
    // Backend returns: { workspaces: [...], total: N }
    const data = await this.request<{ workspaces: any[]; total: number }>('/api/v1/workspaces', {}, true);
    return (data.workspaces || []).map(this.normalizeWorkspace);
  }

  // Helper to normalize workspace response from backend
  private normalizeWorkspace(data: any): Workspace {
    return {
      id: data.id,
      name: data.name,
      description: data.description,
      ownerId: data.owner_id || data.ownerId,
      answerPolicy: data.answer_policy || data.answerPolicy || 'balanced',
      confidenceThreshold: data.evidence_threshold || data.confidenceThreshold || 0.7,
      createdAt: data.created_at || data.createdAt,
      updatedAt: data.updated_at || data.updatedAt,
      memberCount: data.member_count || data.memberCount,
    };
  }

  async createWorkspace(data: { name: string; description?: string; answerPolicy?: string; confidenceThreshold?: number }): Promise<Workspace> {
    const result = await this.request<any>('/api/v1/workspaces', {
      method: 'POST',
      body: JSON.stringify({
        name: data.name,
        answer_policy: data.answerPolicy,
        evidence_threshold: data.confidenceThreshold,
      }),
    }, true);
    return this.normalizeWorkspace(result);
  }

  async getWorkspace(id: string): Promise<Workspace> {
    const data = await this.request<any>(`/api/v1/workspaces/${id}`, {}, true);
    return this.normalizeWorkspace(data);
  }

  async updateWorkspace(id: string, data: Partial<Workspace>): Promise<Workspace> {
    const result = await this.request<any>(`/api/v1/workspaces/${id}`, {
      method: 'PUT',
      body: JSON.stringify({
        name: data.name,
        answer_policy: data.answerPolicy,
        evidence_threshold: data.confidenceThreshold,
      }),
    }, true);
    return this.normalizeWorkspace(result);
  }

  async deleteWorkspace(id: string): Promise<void> {
    await this.request(`/api/v1/workspaces/${id}`, { method: 'DELETE' }, true);
  }

  async getWorkspaceMembers(workspaceId: string): Promise<WorkspaceMember[]> {
    // Backend returns array of members directly
    const data = await this.request<any[]>(`/api/v1/workspaces/${workspaceId}/members`, {}, true);
    return (Array.isArray(data) ? data : []).map(this.normalizeWorkspaceMember);
  }

  // Helper to normalize workspace member response from backend
  private normalizeWorkspaceMember(data: any): WorkspaceMember {
    return {
      userId: data.user_id || data.userId,
      email: data.email,
      name: data.full_name || data.name || '',
      role: data.role,
      joinedAt: data.joined_at || data.joinedAt,
    };
  }

  async addWorkspaceMember(workspaceId: string, email: string, role: string): Promise<WorkspaceMember> {
    const data = await this.request<any>(`/api/v1/workspaces/${workspaceId}/members`, {
      method: 'POST',
      body: JSON.stringify({ email, role }),
    }, true);
    return this.normalizeWorkspaceMember(data);
  }

  async removeWorkspaceMember(workspaceId: string, userId: string): Promise<void> {
    await this.request(`/api/v1/workspaces/${workspaceId}/members/${userId}`, { method: 'DELETE' }, true);
  }

  // ==========================================================================
  // Document Endpoints
  // ==========================================================================

  async getDocuments(workspaceId: string, params?: { search?: string; tags?: string[]; status?: string; includeArchived?: boolean }): Promise<Document[]> {
    const query = new URLSearchParams();
    query.set('workspace_id', workspaceId);
    if (params?.search) query.set('search', params.search);
    if (params?.tags?.length) query.set('tags', params.tags.join(','));
    if (params?.status) query.set('status', params.status);
    if (params?.includeArchived) query.set('include_archived', 'true');
    const queryStr = query.toString();
    // Backend returns: { documents: [...], total: N }
    const data = await this.request<{ documents: any[]; total: number }>(`/api/v1/documents${queryStr ? `?${queryStr}` : ''}`, {}, true);
    return (data.documents || []).map(this.normalizeDocument);
  }

  // Helper to normalize document response from backend
  private normalizeDocument(data: any): Document {
    return {
      id: data.id,
      workspaceId: data.workspace_id || data.workspaceId,
      name: data.title || data.name,
      originalName: data.original_name || data.originalName || data.title || data.name,
      mimeType: data.mime_type || data.mimeType || 'application/octet-stream',
      size: data.size || 0,
      status: data.status || 'pending',
      version: data.version || 1,
      tags: data.tags || [],
      createdAt: data.created_at || data.createdAt,
      updatedAt: data.updated_at || data.updatedAt,
      indexedAt: data.indexed_at || data.indexedAt,
      chunkCount: data.chunk_count || data.chunkCount,
      categoryId: data.category_id || data.categoryId,
      processingProgress: data.processing_progress || data.processingProgress || 0,
      processingStep: data.processing_step || data.processingStep,
      title: data.title,
    };
  }

  async uploadDocument(workspaceId: string, file: File, tags?: string[]): Promise<Document> {
    // Try presigned upload (MinIO/S3), fall back to FormData upload (local storage)
    try {
      const presignReq = {
        filename: file.name,
        size: file.size,
        mime_type: file.type || undefined,
        tags: tags || [],
      };

      interface PresignedResponse { document_id: string; upload_url: string; }
      const presigned = await this.request<PresignedResponse>(
        `/api/v1/workspaces/${workspaceId}/documents/presigned-upload`,
        { method: 'POST', body: JSON.stringify(presignReq) },
        true
      );

      // If backend returns a file:// URL (local storage), fall back to FormData upload
      if (presigned.upload_url.startsWith('file://')) {
        // Delete the placeholder document created by presigned flow
        try { await this.request(`/api/v1/documents/${presigned.document_id}`, { method: 'DELETE' }, true); } catch { /* ignore */ }
        return this._uploadViaFormData(workspaceId, file, tags);
      }

      // Presigned flow: PUT directly to MinIO/S3
      const uploadRes = await fetch(presigned.upload_url, {
        method: 'PUT',
        body: file,
        headers: { 'Content-Type': file.type || 'application/octet-stream' },
      });

      if (!uploadRes.ok) {
        throw new Error(`Direct storage upload failed: ${uploadRes.status}`);
      }

      const docData = await this.request<any>(
        `/api/v1/documents/${presigned.document_id}/presigned-confirm`,
        { method: 'POST' },
        true
      );
      return this.normalizeDocument(docData);
    } catch (err) {
      // If presigned flow fails entirely, fall back to FormData
      console.warn('Presigned upload failed, falling back to FormData:', err);
      return this._uploadViaFormData(workspaceId, file, tags);
    }
  }

  private async _uploadViaFormData(workspaceId: string, file: File, tags?: string[]): Promise<Document> {
    const formData = new FormData();
    formData.append('file', file);
    if (tags && tags.length > 0) {
      formData.append('tags', JSON.stringify(tags));
    }

    // Use fetch directly — this.request() forces Content-Type: application/json
    // which breaks multipart/form-data uploads
    const headers: Record<string, string> = {};
    if (this.accessToken) {
      headers['Authorization'] = `Bearer ${this.accessToken}`;
    }

    const response = await fetch(`${this.baseUrl}/api/v1/workspaces/${workspaceId}/documents/upload`, {
      method: 'POST',
      body: formData,
      headers,
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => 'Upload failed');
      throw new Error(errorText);
    }

    const docData = await response.json();
    return this.normalizeDocument(docData);
  }

  async getDocument(documentId: string): Promise<Document> {
    const data = await this.request<any>(`/api/v1/documents/${documentId}`, {}, true);
    return this.normalizeDocument(data);
  }

  async updateDocument(documentId: string, data: { name?: string; tags?: string[] }): Promise<Document> {
    return this.request<Document>(`/api/v1/documents/${documentId}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    }, true);
  }

  async deleteDocument(documentId: string): Promise<void> {
    await this.request(`/api/v1/documents/${documentId}`, { method: 'DELETE' }, true);
  }

  async reindexDocument(documentId: string): Promise<Job> {
    return this.request<Job>(`/api/v1/documents/${documentId}/reindex`, { method: 'POST' }, true);
  }

  async getDocumentVersions(documentId: string): Promise<DocumentVersion[]> {
    return this.request<DocumentVersion[]>(`/api/v1/documents/${documentId}/versions`, {}, true);
  }

  async getDocumentChunks(documentId: string): Promise<Chunk[]> {
    return this.request<Chunk[]>(`/api/v1/documents/${documentId}/chunks`, {}, true);
  }

  async getDocumentTags(workspaceId?: string): Promise<{ name: string; count: number }[]> {
    const query = workspaceId ? `?workspace_id=${workspaceId}` : '';
    // Backend returns array directly: [{"name": "tag1", "count": 5}, ...]
    const data = await this.request<any>(`/api/v1/documents/tags${query}`, {}, true);
    return Array.isArray(data) ? data : [];
  }

  async archiveDocument(documentId: string): Promise<void> {
    await this.request(`/api/v1/documents/${documentId}/archive`, { method: 'POST' }, true);
  }

  async restoreDocument(documentId: string): Promise<void> {
    await this.request(`/api/v1/documents/${documentId}/restore`, { method: 'POST' }, true);
  }

  async getDocumentContent(documentId: string): Promise<string> {
    // Fetch full text from MinIO via the /text endpoint (no truncation)
    // Use markdown format for better rendering of DOCX/TXT files
    const fetchText = async (format: 'markdown' | 'text'): Promise<string | null> => {
      const doFetch = () => fetch(`${this.baseUrl}/api/v1/documents/${documentId}/text?format=${format}`, {
        headers: this.accessToken ? { 'Authorization': `Bearer ${this.accessToken}` } : {},
      });

      let res = await doFetch();
      if (res.status === 401 && this.refreshToken) {
        const refreshed = await this.refreshAccessToken();
        if (refreshed) {
          res = await doFetch();
        }
      }

      return res.ok ? await res.text() : null;
    };

    const markdown = await fetchText('markdown');
    if (markdown !== null) return markdown;

    // Fallback: try plain text format
    const text = await fetchText('text');
    if (text !== null) return text;

    // Last fallback: concatenate chunks
    const chunks = await this.getDocumentChunks(documentId);
    return chunks.map(c => c.content).join('\n\n');
  }

  /**
   * Get the INLINE viewing URL for the original document file.
   * Uses mode=inline so the browser renders inside iframe.
   */
  getDocumentDownloadUrl(documentId: string): string {
    const token = this.accessToken;
    const url = `${this.baseUrl}/api/v1/documents/${documentId}/download?mode=inline`;
    return token ? `${url}&token=${token}` : url;
  }

  /**
   * Get the RAW viewing URL for the original document file (no mode forced).
   */
  getDocumentRawUrl(documentId: string): string {
    const token = this.accessToken;
    const url = `${this.baseUrl}/api/v1/documents/${documentId}/download`;
    return token ? `${url}?token=${token}` : url;
  }

  /**
   * Get the ATTACHMENT download URL for saving to disk.
   * Uses mode=attachment so the browser triggers "Save As" dialog.
   */
  getDocumentAttachmentUrl(documentId: string): string {
    const token = this.accessToken;
    const url = `${this.baseUrl}/api/v1/documents/${documentId}/download?mode=attachment`;
    return token ? `${url}&token=${token}` : url;
  }

  /**
   * Download the original document file as a Blob.
   */
  async downloadDocumentBlob(documentId: string, signal?: AbortSignal): Promise<{ blob: Blob; filename: string; mimeType: string }> {
    const doFetch = () => fetch(`${this.baseUrl}/api/v1/documents/${documentId}/download`, {
      headers: this.accessToken ? { 'Authorization': `Bearer ${this.accessToken}` } : {},
      signal,
    });

    let res = await doFetch();
    if (res.status === 401 && this.refreshToken) {
      const refreshed = await this.refreshAccessToken();
      if (refreshed) {
        res = await doFetch();
      }
    }
    if (!res.ok) throw new Error(`Download failed: ${res.status}`);
    const blob = await res.blob();
    const disposition = res.headers.get('Content-Disposition') || '';
    // Parse filename from Content-Disposition
    // Backend sends: filename*=utf-8''encoded_name
    let filename = 'document';
    const utf8Match = disposition.match(/filename\*=utf-8''(.+?)(?:;|$)/i);
    if (utf8Match) {
      try {
        filename = decodeURIComponent(utf8Match[1]);
      } catch {
        filename = utf8Match[1];
      }
    } else {
      const basicMatch = disposition.match(/filename="?(.+?)"?(?:;|$)/);
      if (basicMatch) filename = basicMatch[1];
    }
    const mimeType = res.headers.get('Content-Type') || 'application/octet-stream';
    return { blob, filename, mimeType };
  }

  // ==========================================================================
  // Chat Endpoints
  // ==========================================================================

  async getConversations(workspaceId: string): Promise<Conversation[]> {
    // Backend returns: { items: [...], total: N, limit: N, offset: N }
    const data = await this.request<{ items: any[]; total: number }>(`/api/v1/chat/workspaces/${workspaceId}/conversations`, {}, true);
    return (data.items || []).map(this.normalizeConversation);
  }

  async createConversation(workspaceId: string, title?: string): Promise<Conversation> {
    const data = await this.request<any>(`/api/v1/chat/workspaces/${workspaceId}/conversations`, {
      method: 'POST',
      body: JSON.stringify({ title }),
    }, true);
    return this.normalizeConversation(data);
  }

  // Helper to normalize conversation response from backend
  private normalizeConversation(data: any): Conversation {
    return {
      id: data.id,
      workspaceId: data.workspace_id || data.workspaceId,
      title: data.title || 'New Conversation',
      createdAt: data.created_at || data.createdAt,
      updatedAt: data.updated_at || data.updatedAt,
      messageCount: data.message_count || data.messageCount || 0,
    };
  }

  async getConversation(conversationId: string): Promise<Conversation> {
    return this.request<Conversation>(`/api/v1/chat/conversations/${conversationId}`, {}, true);
  }

  async deleteConversation(conversationId: string): Promise<void> {
    await this.request(`/api/v1/chat/conversations/${conversationId}`, { method: 'DELETE' }, true);
  }

  async getMessages(conversationId: string): Promise<Message[]> {
    // Backend returns: { items: [...], conversation_id }
    const data = await this.request<{ items: any[]; conversation_id: string }>(`/api/v1/chat/conversations/${conversationId}/messages`, {}, true);
    return (data.items || []).map(this.normalizeMessage);
  }

  /**
   * Lazy load citations for a specific message.
   * Use this when user clicks to expand message sources.
   */
  async getMessageCitations(messageId: string): Promise<Citation[]> {
    const data = await this.request<any[]>(`/api/v1/chat/messages/${messageId}/citations`, {}, true);
    return (data || []).map((c: any) => ({
      id: c.id,
      documentId: c.document_id || c.documentId,
      documentTitle: c.document_title || c.documentTitle || c.documentName || '',
      chunkId: c.chunk_id || c.chunkId,
      content: c.content || c.quote || '',
      quote: c.quote,
      page: c.page,
      score: c.score,
    }));
  }

  // Helper to normalize message response from backend
  private normalizeMessage(data: any): Message {
    return {
      id: data.id,
      conversationId: data.conversation_id || data.conversationId,
      role: data.role,
      content: data.content,
      createdAt: data.created_at || data.createdAt,
      // Add model and latency info for CitationNote display
      model: data.model,
      latencyMs: data.latency_ms || data.latencyMs,
      tokenUsage: data.prompt_tokens || data.completion_tokens ? {
        prompt: data.prompt_tokens || 0,
        completion: data.completion_tokens || 0,
      } : data.token_usage || data.tokenUsage,
      citations: (data.citations || []).map((c: any) => ({
        id: c.id,
        documentId: c.document_id || c.documentId,
        documentTitle: c.document_title || c.documentTitle || c.documentName || '',
        chunkId: c.chunk_id || c.chunkId,
        content: c.content || c.quote || '',
        quote: c.quote,
        page: c.page,
        score: c.score,
      })),
      contextStats: data.context_stats || data.contextStats,
    };
  }

  async sendMessage(
    conversationId: string,
    content: string,
    options?: {
      model?: string;
      tags?: string[];
      documentIds?: string[];
      hasImage?: boolean;
      imageData?: string;
      imageMimeType?: string;
    }
  ): Promise<{ userMessage: Message; assistantMessage: Message }> {
    // Backend returns: { user_message: {...}, assistant_message: {...} }
    const data = await this.request<any>(`/api/v1/chat/conversations/${conversationId}/messages`, {
      method: 'POST',
      body: JSON.stringify({
        content,
        model: options?.model,
        tags: options?.tags,
        document_ids: options?.documentIds,
        has_image: options?.hasImage,
      }),
    }, true, 180000); // 180 seconds timeout for RAG queries (can be slow on first request)

    return {
      userMessage: this.normalizeMessage(data.user_message),
      assistantMessage: this.normalizeMessage(data.assistant_message),
    };
  }

  /**
   * Send message with SSE streaming for real-time token display.
   * Uses the /api/v1/chat/stream endpoint.
   */
  async sendMessageStream(
    conversationId: string,
    content: string,
    options: {
      model?: string;
      tags?: string[];
      documentIds?: string[];
      workspaceId: string;
      onProgress?: (step: string, progress: number, message?: string) => void;
      onToken?: (token: string, index: number) => void;
      onMetadata?: (metadata: { model?: string; provider?: string; citations?: Citation[]; quality?: Record<string, any>; quality_warnings?: any[] }) => void;
      onError?: (message: string, code?: string) => void;
      onDone?: (totalTimeMs: number) => void;
      onQualityWarning?: (warning: { type: string; severity: string; message: string }) => void;
      onReplaceResponse?: (newContent: string) => void;
    }
  ): Promise<void> {
    const url = `${this.baseUrl}/api/v1/chat/stream`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.accessToken}`,
        'Accept': 'text/event-stream',
      },
      body: JSON.stringify({
        question: content,
        workspace_id: options.workspaceId,
        conversation_id: conversationId,
        model: options.model,
        tags: options.tags,
        document_ids: options.documentIds,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Stream failed: ${errorText}`);
    }

    const reader = response.body?.getReader();
    if (!reader) throw new Error('ReadableStream not supported');

    const decoder = new TextDecoder();
    let buffer = '';
    let currentEventType = '';

    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          // Track SSE event type
          if (line.startsWith('event:')) {
            currentEventType = line.slice(6).trim();
            continue;
          }

          if (line.startsWith('data:')) {
            const dataStr = line.slice(5).trim();
            if (!dataStr || dataStr === '{}') continue;

            try {
              const data = JSON.parse(dataStr);

              // Route based on event type (preferred) or data fields (fallback)
              switch (currentEventType) {
                case 'progress':
                  options.onProgress?.(data.step, data.progress, data.message);
                  break;
                case 'token':
                  options.onToken?.(data.content, data.index);
                  break;
                case 'metadata':
                  options.onMetadata?.({
                    model: data.model,
                    provider: data.provider,
                    citations: data.citations?.map((c: any) => ({
                      chunkId: c.chunk_id || c.chunkId,
                      documentId: c.document_id || c.documentId,
                      documentTitle: c.document_title || c.documentTitle || '',
                      content: c.content || '',
                      page: c.page,
                      score: c.score,
                    })),
                    quality: data.quality,
                    quality_warnings: data.quality_warnings,
                  });
                  break;
                case 'error':
                  options.onError?.(data.message, data.code);
                  break;
                case 'done':
                  options.onDone?.(data.total_time_ms);
                  break;
                case 'quality_warning':
                  options.onQualityWarning?.(data);
                  break;
                case 'replace_response':
                  options.onReplaceResponse?.(data.content);
                  break;
                default:
                  // Fallback: detect by data fields (backward compat)
                  if (data.step !== undefined && data.progress !== undefined) {
                    options.onProgress?.(data.step, data.progress, data.message);
                  } else if (data.content !== undefined && data.index !== undefined) {
                    options.onToken?.(data.content, data.index);
                  } else if (data.model !== undefined || data.provider !== undefined || data.citations !== undefined) {
                    options.onMetadata?.({
                      model: data.model,
                      provider: data.provider,
                      citations: data.citations?.map((c: any) => ({
                        chunkId: c.chunk_id || c.chunkId,
                        documentId: c.document_id || c.documentId,
                        documentTitle: c.document_title || c.documentTitle || '',
                        content: c.content || '',
                        page: c.page,
                        score: c.score,
                      })),
                      quality: data.quality,
                      quality_warnings: data.quality_warnings,
                    });
                  } else if (data.message !== undefined && data.code !== undefined) {
                    options.onError?.(data.message, data.code);
                  } else if (data.total_time_ms !== undefined) {
                    options.onDone?.(data.total_time_ms);
                  }
                  break;
              }

              // Reset event type after processing
              currentEventType = '';
            } catch (e) {
              console.warn('Failed to parse SSE data:', dataStr, e);
            }
          }
        }
      }
    } finally {
      reader.releaseLock();
    }
  }

  async queryRAG(request: ChatQueryRequest & { ragOnly?: boolean; imageData?: string; imageMimeType?: string }): Promise<ChatQueryResponse> {
    // Backend expects: { question, workspace_id, document_ids, tags, top_k, model, has_image, rag_only, image_data, image_mime_type }
    const data = await this.request<any>('/api/v1/chat/query', {
      method: 'POST',
      body: JSON.stringify({
        question: request.question,
        workspace_id: request.workspaceId,
        document_ids: request.documentIds,
        tags: request.tags,
        top_k: request.topK || 5,
        model: request.model,
        has_image: !!request.imageData,
        rag_only: request.ragOnly,
        image_data: request.imageData,
        image_mime_type: request.imageMimeType || 'image/jpeg',
      }),
    }, true, 120000); // 120 seconds timeout for complex queries

    // Normalize response
    return {
      answer: data.answer,
      citations: (data.citations || []).map((c: any) => ({
        documentId: c.document_id || c.documentId,
        documentName: c.document_title || c.documentName || '',
        chunkId: c.chunk_id || c.chunkId,
        content: c.content,
        page: c.page,
        score: c.score,
      })),
      model: data.model || '',
      latencyMs: data.latency_ms || data.latencyMs || 0,
      evidenceScore: data.policy_evaluation?.best_score || 0,
      isGrounded: data.policy_evaluation?.is_grounded ?? true,
      tokenUsage: data.prompt_tokens || data.completion_tokens ? {
        prompt: data.prompt_tokens || 0,
        completion: data.completion_tokens || 0,
      } : undefined,
      contextStats: data.context_stats || data.contextStats,
      // Image generation support
      images: data.images,
      isImageResponse: data.is_image_response || false,
    };
  }

  async chatDirect(request: { question: string; model?: string; imageData?: string; imageMimeType?: string }): Promise<ChatQueryResponse> {
    // Direct chat without RAG - just LLM (supports image generation and image analysis)
    const data = await this.request<any>('/api/v1/chat/direct', {
      method: 'POST',
      body: JSON.stringify({
        question: request.question,
        model: request.model,
        image_data: request.imageData,
        image_mime_type: request.imageMimeType || 'image/jpeg',
      }),
    }, true, 120000); // 120 seconds timeout for LLM responses

    return {
      answer: data.answer || data.content || '',
      citations: [],
      model: data.model || '',
      latencyMs: data.latency_ms || data.latencyMs || 0,
      evidenceScore: 0,
      isGrounded: false,
      tokenUsage: data.prompt_tokens || data.completion_tokens ? {
        prompt: data.prompt_tokens || 0,
        completion: data.completion_tokens || 0,
      } : undefined,
      // Image generation support
      images: data.images,
      isImageResponse: data.is_image_response || false,
    };
  }

  // ==========================================================================
  // Job Endpoints
  // ==========================================================================

  async getJobs(params?: { type?: string; status?: string; limit?: number }): Promise<Job[]> {
    const query = new URLSearchParams();
    if (params?.type) query.set('type', params.type);
    if (params?.status) query.set('status', params.status);
    if (params?.limit) query.set('limit', params.limit.toString());
    const queryStr = query.toString();
    return this.request<Job[]>(`/api/v1/jobs${queryStr ? `?${queryStr}` : ''}`, {}, true);
  }

  async getJobById(jobId: string): Promise<Job> {
    return this.request<Job>(`/api/v1/jobs/${jobId}`, {}, true);
  }

  async cancelJob(jobId: string): Promise<void> {
    await this.request(`/api/v1/jobs/${jobId}/cancel`, { method: 'POST' }, true);
  }

  // ==========================================================================
  // Model Endpoints
  // ==========================================================================

  async getModels(): Promise<AIModel[]> {
    const data = await this.request<{ models: AIModel[]; total: number }>('/api/v1/models', {});
    return data.models || [];
  }

  async getProviderHealth(): Promise<ProviderHealth[]> {
    // Backend returns: { providers: [...], cloudcode_details: ..., health_monitor: ..., timestamp: ... }
    const data = await this.request<{ providers: any[]; cloudcode_details?: any; health_monitor?: any }>('/api/v1/health/providers', {});
    return (data.providers || []).map((p: any) => ({
      name: p.name,
      available: p.available,
      responseTimeMs: p.response_time_ms || p.responseTimeMs,
      quotaExceeded: p.quota_exceeded || p.quotaExceeded,
      lastCheck: p.last_check || p.lastCheck,
    }));
  }

  // ==========================================================================
  // Cloud Code Endpoints
  // ==========================================================================

  async getCloudCodeAccounts(): Promise<any[]> {
    const data = await this.request<any>('/api/v1/cloudcode/accounts', {}, true);
    if (Array.isArray(data)) return data;
    if (data && Array.isArray(data.accounts)) return data.accounts;
    if (data && Array.isArray(data.items)) return data.items;
    return [];
  }

  async getCloudCodeStatistics(): Promise<any> {
    // Backend returns: { total_accounts, available_accounts, total_requests, total_failures }
    const data = await this.request<any>('/api/v1/cloudcode/statistics', {}, true);
    return {
      totalAccounts: data.total_accounts || data.totalAccounts || 0,
      avgClaudeQuota: data.avg_claude_quota || data.avgClaudeQuota || 0,
      avgGeminiQuota: data.avg_gemini_quota || data.avgGeminiQuota || 0,
      avgGeminiImageQuota: data.avg_gemini_image_quota || data.avgGeminiImageQuota || 0,
      lowQuotaAccounts: data.low_quota_accounts || data.lowQuotaAccounts || 0,
    };
  }

  async refreshCloudCodeAccount(accountId: string): Promise<any> {
    return this.request<any>(`/api/v1/cloudcode/accounts/${accountId}/refresh`, { method: 'POST' }, true);
  }

  async refreshAllCloudCodeAccounts(): Promise<{ total: number; success: number; failed: number; results: Record<string, boolean> }> {
    return this.request<{ total: number; success: number; failed: number; results: Record<string, boolean> }>(
      '/api/v1/cloudcode/accounts/refresh-all',
      { method: 'POST' },
      true
    );
  }

  async addCloudCodeAccount(email: string, refreshToken: string): Promise<any> {
    return this.request<any>('/api/v1/cloudcode/accounts', {
      method: 'POST',
      body: JSON.stringify({ email, refresh_token: refreshToken }),
    }, true);
  }

  async removeCloudCodeAccount(accountId: string): Promise<void> {
    await this.request(`/api/v1/cloudcode/accounts/${accountId}`, { method: 'DELETE' }, true);
  }

  async setDefaultCloudCodeAccount(accountId: string): Promise<void> {
    await this.request(`/api/v1/cloudcode/accounts/${accountId}/default`, { method: 'POST' }, true);
  }

  async getCloudCodeAccountDetails(accountId: string): Promise<any> {
    return this.request<any>(`/api/v1/cloudcode/accounts/${accountId}/details`, {}, true);
  }

  async startCloudCodeOAuth(): Promise<{ authUrl: string; sessionId: string }> {
    return this.request<{ authUrl: string; sessionId: string }>('/api/v1/cloudcode/oauth/start', { method: 'POST' }, true);
  }

  async checkCloudCodeOAuthStatus(sessionId: string): Promise<{ completed: boolean; success?: boolean; error?: string }> {
    return this.request<{ completed: boolean; success?: boolean; error?: string }>(`/api/v1/cloudcode/oauth/status/${sessionId}`, {}, true);
  }

  // ==========================================================================
  // API Keys Endpoints (for free providers)
  // ==========================================================================

  async getApiKeys(): Promise<{ provider: string; hasKey: boolean; lastUpdated?: string; isValid?: boolean }[]> {
    return this.request<any[]>('/api/v1/apikeys', {}, true);
  }

  async saveApiKey(provider: string, apiKey: string): Promise<void> {
    await this.request('/api/v1/apikeys', {
      method: 'POST',
      body: JSON.stringify({ provider, api_key: apiKey }),
    }, true);
  }

  async deleteApiKey(provider: string): Promise<void> {
    await this.request(`/api/v1/apikeys/${provider}`, { method: 'DELETE' }, true);
  }

  async testApiKey(provider: string): Promise<{ valid: boolean; error?: string }> {
    return this.request<{ valid: boolean; error?: string }>(`/api/v1/apikeys/${provider}/test`, { method: 'POST' }, true);
  }

  // ==========================================================================
  // Analytics Endpoints
  // ==========================================================================

  async getUsageStats(params?: { startDate?: string; endDate?: string; workspaceId?: string }): Promise<UsageStats> {
    const query = new URLSearchParams();
    if (params?.startDate) query.set('start_date', params.startDate);
    if (params?.endDate) query.set('end_date', params.endDate);
    if (params?.workspaceId) query.set('workspace_id', params.workspaceId);
    const queryStr = query.toString();
    return this.request<UsageStats>(`/api/v1/analytics/usage${queryStr ? `?${queryStr}` : ''}`, {}, true);
  }

  async getDashboardStats(): Promise<any> {
    return this.request<any>('/api/v1/analytics/dashboard', {}, true);
  }

  // ==========================================================================
  // OCR Endpoints (existing)
  // ==========================================================================

  async extractOcr(file: File, settings: OcrSettings, sync: boolean = false): Promise<{ jobId?: string; result?: OcrResult }> {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('settings_json', JSON.stringify({
      parser: settings.parser || 'docling',
      parse_method: settings.parseMethod || 'auto',
      language: settings.language || 'auto',
      mode: settings.mode || 'balanced',
      preserveLayout: settings.preserveLayout ?? true,
      returnLayout: settings.returnLayout ?? true,
      startPage: settings.startPage,
      endPage: settings.endPage,
      preprocess: {
        autoOrientation: settings.preprocess?.autoOrient ?? true,
        deskew: settings.preprocess?.deskew ?? true,
        denoise: settings.preprocess?.denoise ?? false,
        binarize: settings.preprocess?.binarize ?? false,
        contrastBoost: settings.preprocess?.contrastBoost ?? false,
      },
      extract: {
        tables: settings.extract?.tables ?? true,
        equations: settings.extract?.equations ?? true,
        images: settings.extract?.images ?? false,
      }
    }));

    const url = new URL(`${this.baseUrl}/api/ocr/extract`);
    if (sync) url.searchParams.set('sync', 'true');

    const response = await fetch(url.toString(), { method: 'POST', body: formData });
    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Network error' }));
      throw new Error(error.detail || `HTTP ${response.status}`);
    }

    const data = await response.json();
    if (sync && data.result) {
      return { result: this.transformBackendResult(data.result) };
    }
    return { jobId: data.jobId };
  }

  async getJob(jobId: string): Promise<{ status: string; step: string; percent: number; message: string; result?: OcrResult; error?: string }> {
    const response = await fetch(`${this.baseUrl}/api/jobs/${jobId}`);
    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Network error' }));
      throw new Error(error.detail || `HTTP ${response.status}`);
    }
    const data = await response.json();
    return {
      status: data.status,
      step: data.step,
      percent: data.percent,
      message: data.message,
      result: data.result ? this.transformBackendResult(data.result) : undefined,
      error: data.error
    };
  }

  async convertTextToFile(text: string, options: ConvertOptions): Promise<Blob> {
    const response = await fetch(`${this.baseUrl}/api/convert`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        text,
        format: options.format,
        fileName: options.fileName || 'output',
        includeMetadata: options.includeMetadata ?? true,
        pdfOptions: options.format === 'pdf' ? {
          pageSize: options.pageSize || 'A4',
          fontSize: options.fontSize || 12
        } : undefined
      }),
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Network error' }));
      throw new Error(error.detail || `HTTP ${response.status}`);
    }
    return response.blob();
  }

  async ragIngest(docId?: string, jobId?: string): Promise<void> {
    const response = await fetch(`${this.baseUrl}/api/rag/ingest`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ docId, jobId }),
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Network error' }));
      throw new Error(error.detail || `HTTP ${response.status}`);
    }
  }

  async ragQuery(question: string, mode: string = 'hybrid', vlmEnhanced: boolean = true): Promise<{ answer: string; contexts: any[] }> {
    const response = await fetch(`${this.baseUrl}/api/rag/query`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ question, mode, vlmEnhanced }),
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Network error' }));
      throw new Error(error.detail || `HTTP ${response.status}`);
    }
    return response.json();
  }

  async checkHealth(): Promise<{ ok: boolean; version: string; parserDefault: string; enableRag: boolean; ollamaReachable: boolean; aiProviders?: any; cloudCode?: any }> {
    const response = await fetch(`${this.baseUrl}/api/health`);
    if (!response.ok) throw new Error(`Health check failed: HTTP ${response.status}`);
    return response.json();
  }

  private transformBackendResult(backendResult: any): OcrResult {
    const pages: OcrPage[] = backendResult.pages?.map((page: any) => ({
      page: page.page,
      text: page.text,
      confidence: page.confidence || 0.9,
      lowConfidenceRanges: []
    })) || [];

    const layoutPages: OcrLayoutPage[] = backendResult.layout?.pages?.map((page: any) => ({
      page: page.page,
      width: page.width || 1,
      height: page.height || 1.414,
      blocks: page.blocks?.map((block: any) => ({
        id: `block-${block.type}-${Math.random()}`,
        bbox: block.bbox,
        lines: block.lines?.map((line: any) => ({
          text: line.text,
          confidence: line.confidence || 0.9,
          bbox: line.bbox,
          words: line.words?.map((word: any) => ({
            text: word.text,
            bbox: word.bbox,
            confidence: word.confidence || 0.9
          })) || []
        })) || []
      })) || []
    })) || [];

    const displayText = backendResult.enhancedText || backendResult.fullText || '';

    return {
      fullText: displayText,
      pages,
      layoutPages,
      language: backendResult.meta?.language || 'auto',
      avgConfidence: backendResult.meta?.avgConfidence || 0.9,
      structured: {
        tables: backendResult.structured?.tables || [],
        keyValues: [],
        entities: []
      },
      version: 'v1',
      status: 'done' as const
    };
  }

  // Document Compare API
  async compareDocuments(formData: FormData): Promise<any> {
    const headers: Record<string, string> = {};
    if (this.accessToken) {
      headers['Authorization'] = `Bearer ${this.accessToken}`;
    }
    // Don't set Content-Type for FormData - browser will set it with boundary
    const response = await fetch(`${this.baseUrl}/api/v1/compare`, {
      method: 'POST',
      headers,
      body: formData,
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Network error' }));
      throw new Error(error.detail || `HTTP ${response.status}`);
    }
    return response.json();
  }

  async compareVersions(documentId: string, versionA: number, versionB: number): Promise<any> {
    return this.request<any>('/api/v1/compare/versions', {
      method: 'POST',
      body: JSON.stringify({ document_id: documentId, version_a: versionA, version_b: versionB }),
    }, true);
  }

  async getCompareResult(compareId: string): Promise<any> {
    return this.request<any>(`/api/v1/compare/${compareId}`, {}, true);
  }

  // ==========================================================================
  // Category Endpoints
  // ==========================================================================

  async getCategories(workspaceId: string): Promise<Category[]> {
    const data = await this.request<{ categories: any[]; total: number }>(
      `/api/v1/categories/${workspaceId}`, {}, true
    );
    return (data.categories || []).map(this.normalizeCategory);
  }

  private normalizeCategory(data: any): Category {
    return {
      id: data.id,
      workspaceId: data.workspace_id || data.workspaceId,
      name: data.name,
      slug: data.slug,
      description: data.description,
      contentSummary: data.content_summary || data.contentSummary,
      keywords: data.keywords || [],
      icon: data.icon,
      color: data.color,
      displayOrder: data.display_order || data.displayOrder || 0,
      isAutoGenerated: data.is_auto_generated ?? data.isAutoGenerated ?? true,
      documentCount: data.document_count || data.documentCount || 0,
    };
  }

  async createCategory(workspaceId: string, data: { name: string; description?: string; icon?: string; color?: string }): Promise<Category> {
    const result = await this.request<any>(`/api/v1/categories/${workspaceId}`, {
      method: 'POST',
      body: JSON.stringify(data),
    }, true);
    return this.normalizeCategory(result);
  }

  async updateCategory(categoryId: string, data: { name?: string; description?: string; icon?: string; color?: string; displayOrder?: number }): Promise<Category> {
    const result = await this.request<any>(`/api/v1/categories/${categoryId}`, {
      method: 'PUT',
      body: JSON.stringify({
        name: data.name,
        description: data.description,
        icon: data.icon,
        color: data.color,
        display_order: data.displayOrder,
      }),
    }, true);
    return this.normalizeCategory(result);
  }

  async deleteCategory(categoryId: string): Promise<void> {
    await this.request(`/api/v1/categories/${categoryId}`, { method: 'DELETE' }, true);
  }

  async refreshCategorySummary(categoryId: string): Promise<{ summary: string }> {
    return this.request<{ summary: string }>(`/api/v1/categories/${categoryId}/refresh-summary`, { method: 'POST' }, true);
  }

  async categorizeDocument(documentId: string): Promise<{
    success?: boolean;
    pending?: boolean;
    message?: string;
    categoryId: string | null;
    categoryName: string | null;
    documentSummary?: string;
    mainHeadings?: string[]
  }> {
    const data = await this.request<any>(`/api/v1/categories/documents/${documentId}/categorize`, { method: 'POST' }, true);
    return {
      success: data.success,
      pending: data.pending,
      message: data.message,
      categoryId: data.category_id || data.categoryId || null,
      categoryName: data.category_name || data.categoryName || null,
      documentSummary: data.document_summary || data.documentSummary,
      mainHeadings: data.main_headings || data.mainHeadings,
    };
  }

  async setDocumentCategory(documentId: string, categoryId: string | null): Promise<void> {
    await this.request(`/api/v1/categories/documents/${documentId}/category`, {
      method: 'PUT',
      body: JSON.stringify({ category_id: categoryId }),
    }, true);
  }

  // ==========================================================================
  // Memori (Memory Management) Endpoints
  // ==========================================================================

  /**
   * List all facts for an entity (no semantic search)
   */
  async listFacts(params: {
    entityId: string;
    workspaceId: string;
    limit?: number;
    offset?: number;
  }): Promise<Array<{
    id: number;
    content: string;
    similarity: number;
    lexicalScore: number;
    rankScore: number;
  }>> {
    const queryParams = new URLSearchParams();
    queryParams.set('workspace_id', params.workspaceId);
    if (params.limit) queryParams.set('limit', params.limit.toString());
    if (params.offset) queryParams.set('offset', params.offset.toString());

    const data = await this.request<any>(
      `/api/v1/memori/facts/${params.entityId}?${queryParams}`,
      { method: 'GET' },
      true
    );

    return (data || []).map((f: any) => ({
      id: f.id,
      content: f.content,
      similarity: f.similarity || 0,
      lexicalScore: f.lexical_score || f.lexicalScore || 0,
      rankScore: f.rank_score || f.rankScore || 0,
      importanceScore: f.importance_score || f.importanceScore || 1.0,
    }));
  }

  /**
   * Recall relevant facts for a query using semantic similarity
   */
  async recallFacts(params: {
    query: string;
    workspaceId: string;
    entityId?: string;
    conversationId?: string;
    limit?: number;
  }): Promise<{
    facts: Array<{
      id: number;
      content: string;
      similarity: number;
      lexicalScore: number;
      rankScore: number;
    }>;
    query: string;
    totalFound: number;
  }> {
    const queryParams = new URLSearchParams();
    queryParams.set('workspace_id', params.workspaceId);
    if (params.entityId) queryParams.set('entity_id', params.entityId);
    if (params.conversationId) queryParams.set('conversation_id', params.conversationId);

    const data = await this.request<any>(`/api/v1/memori/recall?${queryParams}`, {
      method: 'POST',
      body: JSON.stringify({
        query: params.query,
        limit: params.limit || 5,
      }),
    }, true);

    return {
      facts: (data.facts || []).map((f: any) => ({
        id: f.id,
        content: f.content,
        similarity: f.similarity || 0,
        lexicalScore: f.lexical_score || f.lexicalScore || 0,
        rankScore: f.rank_score || f.rankScore || 0,
        importanceScore: f.importance_score || f.importanceScore || 1.0,
      })),
      query: data.query,
      totalFound: data.total_found || data.totalFound || 0,
    };
  }

  /**
   * Add facts about an entity
   */
  async addFacts(params: {
    entityId: string;
    workspaceId: string;
    facts: Array<{ content: string; importanceScore?: number }>;
    conversationId?: string;
  }): Promise<number[]> {
    const queryParams = new URLSearchParams();
    queryParams.set('workspace_id', params.workspaceId);
    if (params.conversationId) queryParams.set('conversation_id', params.conversationId);

    return this.request<number[]>(`/api/v1/memori/facts/${params.entityId}?${queryParams}`, {
      method: 'POST',
      body: JSON.stringify(params.facts.map(f => ({
        content: f.content,
        importance_score: f.importanceScore || 1.0,
      }))),
    }, true);
  }

  /**
   * Get knowledge graph for an entity
   */
  async getKnowledgeGraph(params: {
    entityId: string;
    workspaceId: string;
    limit?: number;
  }): Promise<Array<{
    subjectName: string;
    subjectType?: string;
    predicate: string;
    objectName: string;
    objectType?: string;
  }>> {
    const queryParams = new URLSearchParams();
    queryParams.set('workspace_id', params.workspaceId);
    if (params.limit) queryParams.set('limit', params.limit.toString());

    const data = await this.request<any[]>(`/api/v1/memori/knowledge-graph/${params.entityId}?${queryParams}`, {}, true);

    return (data || []).map((t: any) => ({
      subjectName: t.subject_name || t.subjectName,
      subjectType: t.subject_type || t.subjectType,
      predicate: t.predicate,
      objectName: t.object_name || t.objectName,
      objectType: t.object_type || t.objectType,
    }));
  }

  /**
   * Get memory statistics for an entity
   */
  async getMemoryStats(params: {
    entityId: string;
    workspaceId: string;
  }): Promise<{
    entityId: string;
    totalFacts: number;
    totalTriples: number;
    avgImportance: number;
  }> {
    const queryParams = new URLSearchParams();
    queryParams.set('workspace_id', params.workspaceId);

    const data = await this.request<any>(`/api/v1/memori/stats/${params.entityId}?${queryParams}`, {}, true);

    return {
      entityId: data.entity_id || data.entityId,
      totalFacts: data.total_facts || data.totalFacts || 0,
      totalTriples: data.total_triples || data.totalTriples || 0,
      avgImportance: data.avg_importance || data.avgImportance || 0,
    };
  }

  /**
   * Update fact importance score (Memory Intelligence Layer)
   */
  async updateFactImportance(
    factId: number,
    importanceScore: number,
    workspaceId: string
  ): Promise<{ success: boolean; factId: number; importanceScore: number }> {
    const queryParams = new URLSearchParams();
    queryParams.set('importance_score', importanceScore.toString());
    queryParams.set('workspace_id', workspaceId); // Add workspaceId to query params

    return this.request(
      `/api/v1/memori/facts/${factId}/importance?${queryParams}`,
      { method: 'PATCH' },
      true
    );
  }

  /**
   * Pin or unpin a fact (Memory Intelligence Layer)
   */
  async pinFact(
    factId: number,
    pinned: boolean,
    workspaceId: string
  ): Promise<{ success: boolean; factId: number; pinned: boolean; importanceScore: number }> {
    const queryParams = new URLSearchParams();
    queryParams.set('pinned', pinned.toString());
    queryParams.set('workspace_id', workspaceId); // Add workspaceId to query params

    return this.request(
      `/api/v1/memori/facts/${factId}/pin?${queryParams}`,
      { method: 'POST' },
      true
    );
  }

  async deleteFact(factId: number, workspaceId: string): Promise<void> {
    const queryParams = new URLSearchParams();
    queryParams.set('workspace_id', workspaceId);

    await this.request(
      `/api/v1/memori/facts/${factId}?${queryParams}`,
      { method: 'DELETE' },
      true
    );
  }

  // ============================================================================
  // PROGRESSIVE DISCLOSURE SEARCH (Phase 2 & 6)
  // ============================================================================

  /**
   * Layer 1: Get compact search index
   */
  async searchIndex(params: {
    query: string;
    workspaceId: string;
    limit?: number;
  }): Promise<Array<{
    id: string;
    document_id: string;
    document_title: string;
    snippet: string;
    score?: number;
    rerank_score?: number;
    page_start?: number;
    created_at: string;
  }>> {
    const queryParams = new URLSearchParams();
    queryParams.set('query', params.query);
    queryParams.set('workspace_id', params.workspaceId);
    if (params.limit) queryParams.set('limit', params.limit.toString());

    return this.request(
      `/api/v1/search/index?${queryParams}`,
      { method: 'GET' },
      true
    );
  }

  /**
   * Layer 2: Get chronological timeline for a chunk
   */
  async getTimeline(params: {
    anchorId: string;
    depthBefore?: number;
    depthAfter?: number;
  }): Promise<Array<{
    chunk_id: string;
    document_title: string;
    snippet: string;
    page_start?: number;
    created_at: string;
    is_anchor: boolean;
  }>> {
    const queryParams = new URLSearchParams();
    queryParams.set('anchor_id', params.anchorId);
    if (params.depthBefore) queryParams.set('depth_before', params.depthBefore.toString());
    if (params.depthAfter) queryParams.set('depth_after', params.depthAfter.toString());

    return this.request(
      `/api/v1/search/timeline?${queryParams}`,
      { method: 'GET' },
      true
    );
  }

  /**
   * Layer 3: Get full details for chunks
   */
  async getChunkDetails(chunkIds: string[]): Promise<Array<{
    id: string;
    document_id: string;
    document_title: string;
    content: string;
    page_start?: number;
    page_end?: number;
    section_title?: string;
    created_at: string;
  }>> {
    return this.request(
      `/api/v1/search/details`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ chunk_ids: chunkIds }),
      },
      true
    );
  }
}

// Global API client instance
export const apiClient = new ApiClient();

// ============================================================================
// Legacy Functions (for backward compatibility)
// ============================================================================

const JOB_STATUSES: BatchJob['status'][] = ['queued', 'preprocessing', 'running', 'postprocessing', 'done'];
let jobs: BatchJob[] = [];

type ProgressCallback = (progress: ProgressState) => void;
const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export async function uploadAndExtractText(
  file: File,
  settings: OcrSettings,
  onProgress?: ProgressCallback
): Promise<OcrResult> {
  onProgress?.({ current: 1, total: 3, label: 'Uploading to server...' });

  try {
    const result = await apiClient.extractOcr(file, settings, true);
    onProgress?.({ current: 2, total: 3, label: 'Processing with Docling...' });

    if (result.result) {
      onProgress?.({ current: 3, total: 3, label: 'Complete' });
      return result.result;
    }
    throw new Error('No result returned from backend');
  } catch (error) {
    console.error('OCR processing failed:', error);
    throw error;
  }
}

export async function convertTextToFile(
  text: string,
  options: ConvertOptions,
  onProgress?: ProgressCallback
): Promise<Blob> {
  onProgress?.({ current: 1, total: 2, label: 'Converting with backend...' });

  try {
    const blob = await apiClient.convertTextToFile(text, options);
    onProgress?.({ current: 2, total: 2, label: 'Complete' });
    return blob;
  } catch (error) {
    console.warn('Backend conversion failed:', error);

    if (options.format === 'pdf' || options.format === 'docx') {
      throw new Error(`Backend required for ${options.format.toUpperCase()} conversion.`);
    }

    onProgress?.({ current: 2, total: 2, label: 'Using local conversion...' });

    const mimeTypes: Record<ConvertOptions['format'], string> = {
      txt: 'text/plain',
      md: 'text/markdown',
      json: 'application/json',
      pdf: 'application/pdf',
      docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    };

    let content = text;
    if (options.format === 'json') {
      content = JSON.stringify({ content: text, meta: options.includeMetadata ? { generatedAt: new Date().toISOString(), length: text.length } : undefined }, null, 2);
    } else if (options.format === 'md') {
      content = `# Converted Output\n\n${text}`;
    }

    return new Blob([content], { type: mimeTypes[options.format] });
  }
}

export async function createBatchJobs(files: File[], settings: OcrSettings): Promise<BatchJob[]> {
  const newJobs: BatchJob[] = files.map((file) => ({
    id: generateId('job'),
    fileName: file.name,
    type: 'ocr',
    status: 'queued',
    progress: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attempt: 1,
    message: `Lang: ${settings.language}, Mode: ${settings.mode}`,
  }));

  jobs = [...newJobs, ...jobs].slice(0, 20);
  newJobs.forEach((job) => simulateJob(job.id));
  await delay(200);
  return newJobs;
}

function simulateJob(jobId: string) {
  let idx = 0;
  const timer = setInterval(() => {
    const job = jobs.find((j) => j.id === jobId);
    if (!job) { clearInterval(timer); return; }
    job.status = JOB_STATUSES[Math.min(idx, JOB_STATUSES.length - 1)];
    job.progress = Math.min(100, Math.round(((idx + 1) / JOB_STATUSES.length) * 100));
    job.updatedAt = new Date().toISOString();
    if (idx >= JOB_STATUSES.length - 1) clearInterval(timer);
    idx += 1;
  }, 550);
}

export async function getJobs(): Promise<BatchJob[]> {
  await delay(120);
  return jobs.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
}

export async function readTextFile(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result || ''));
    reader.onerror = () => reject(reader.error);
    reader.readAsText(file);
  });
}

export async function startAsyncOcrJob(file: File, settings: OcrSettings): Promise<string> {
  const result = await apiClient.extractOcr(file, settings, false);
  if (!result.jobId) throw new Error('Failed to start OCR job');
  return result.jobId;
}

export async function pollJobStatus(
  jobId: string,
  onProgress?: (progress: { step: string; percent: number; message: string }) => void
): Promise<OcrResult> {
  const maxAttempts = 120;
  let attempts = 0;

  while (attempts < maxAttempts) {
    try {
      const jobStatus = await apiClient.getJob(jobId);
      onProgress?.({ step: jobStatus.step, percent: jobStatus.percent, message: jobStatus.message });
      if (jobStatus.status === 'done' && jobStatus.result) return jobStatus.result;
      if (jobStatus.status === 'error') throw new Error(jobStatus.error || 'Job failed');
      await delay(1000);
      attempts++;
    } catch (error) {
      console.error('Error polling job status:', error);
      attempts++;
      await delay(1000);
    }
  }
  throw new Error('Job timeout - processing took too long');
}

export async function createBatchJobsWithBackend(files: File[], settings: OcrSettings): Promise<BatchJob[]> {
  const newJobs: BatchJob[] = [];

  for (const file of files) {
    try {
      const jobId = await startAsyncOcrJob(file, settings);
      const batchJob: BatchJob = {
        id: jobId,
        fileName: file.name,
        type: 'ocr',
        status: 'queued',
        progress: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        attempt: 1,
        message: `Parser: ${settings.parser || 'docling'}`,
      };
      newJobs.push(batchJob);

      pollJobStatus(jobId, (progress) => {
        const job = jobs.find(j => j.id === jobId);
        if (job) {
          job.status = progress.step as BatchJob['status'];
          job.progress = progress.percent;
          job.message = progress.message;
          job.updatedAt = new Date().toISOString();
        }
      }).then(() => {
        const job = jobs.find(j => j.id === jobId);
        if (job) { job.status = 'done'; job.progress = 100; job.updatedAt = new Date().toISOString(); job.resultUrl = `#job-${jobId}`; }
      }).catch((error) => {
        const job = jobs.find(j => j.id === jobId);
        if (job) { job.status = 'done'; job.progress = 100; job.message = `Error: ${error.message}`; job.updatedAt = new Date().toISOString(); }
      });
    } catch (error) {
      const id = generateId('job');
      newJobs.push({ id, fileName: file.name, type: 'ocr', status: 'queued', progress: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), attempt: 1, message: `Fallback mode: ${error}` });
      simulateJob(id);
    }
  }

  jobs = [...newJobs, ...jobs].slice(0, 20);
  return newJobs;
}

// Convenience export for api object
export const api = {
  compareDocuments: (formData: FormData) => apiClient.compareDocuments(formData),
  compareVersions: (documentId: string, versionA: number, versionB: number) =>
    apiClient.compareVersions(documentId, versionA, versionB),
  getCompareResult: (compareId: string) => apiClient.getCompareResult(compareId),
};

// ============================================================================
// Extraction Types
// ============================================================================

export type FieldType = 'text' | 'number' | 'date' | 'boolean' | 'currency' | 'email' | 'phone' | 'url' | 'list' | 'object';

export interface ValidationRule {
  type: string;
  value?: any;
  message?: string;
}

export interface TemplateField {
  name: string;
  type: FieldType;
  description?: string;
  required: boolean;
  validation_rules: ValidationRule[];
  examples: string[];
  default_value?: any;
}

export interface ExtractionTemplate {
  id: string;
  workspace_id: string;
  name: string;
  description?: string;
  fields: TemplateField[];
  created_at: string;
  updated_at?: string;
  created_by?: string;
}

export interface ExtractedField {
  field_name: string;
  field_type: FieldType;
  value: any;
  raw_text?: string;
  confidence: number;
  source_location?: string;
  source_chunk_id?: string;
  validation_passed: boolean;
  validation_errors: string[];
  needs_review: boolean;
}

export interface ExtractionResult {
  id: string;
  workspace_id: string;
  template_id: string;
  template_name: string;
  document_id: string;
  document_title?: string;
  fields: ExtractedField[];
  overall_confidence: number;
  fields_extracted: number;
  fields_failed: number;
  fields_need_review: number;
  created_at: string;
}

export type ExportFormat = 'json' | 'csv' | 'excel';

// ============================================================================
// Extraction API Functions
// ============================================================================

export async function getExtractionTemplates(workspaceId?: string): Promise<{ templates: ExtractionTemplate[]; total: number }> {
  const query = workspaceId ? `?workspace_id=${workspaceId}` : '';
  return apiClient.request<{ templates: ExtractionTemplate[]; total: number }>(`/api/v1/extraction/templates${query}`, {}, true);
}

export async function getExtractionTemplate(templateId: string): Promise<ExtractionTemplate> {
  return apiClient.request<ExtractionTemplate>(`/api/v1/extraction/templates/${templateId}`, {}, true);
}

export async function createExtractionTemplate(data: {
  name: string;
  description?: string;
  fields: TemplateField[];
}): Promise<ExtractionTemplate> {
  return apiClient.request<ExtractionTemplate>('/api/v1/extraction/templates', {
    method: 'POST',
    body: JSON.stringify(data),
  }, true);
}

export async function updateExtractionTemplate(templateId: string, data: {
  name?: string;
  description?: string;
  fields?: TemplateField[];
}): Promise<ExtractionTemplate> {
  return apiClient.request<ExtractionTemplate>(`/api/v1/extraction/templates/${templateId}`, {
    method: 'PUT',
    body: JSON.stringify(data),
  }, true);
}

export async function deleteExtractionTemplate(templateId: string): Promise<void> {
  await apiClient.request<void>(`/api/v1/extraction/templates/${templateId}`, {
    method: 'DELETE',
  }, true);
}

export async function extractData(templateId: string, documentId: string): Promise<ExtractionResult> {
  return apiClient.request<ExtractionResult>('/api/v1/extraction/extract', {
    method: 'POST',
    body: JSON.stringify({ template_id: templateId, document_id: documentId }),
  }, true);
}

export async function batchExtractData(templateId: string, documentIds: string[]): Promise<{
  results: ExtractionResult[];
  total_documents: number;
  successful: number;
  failed: number;
}> {
  return apiClient.request<{
    results: ExtractionResult[];
    total_documents: number;
    successful: number;
    failed: number;
  }>('/api/v1/extraction/extract/batch', {
    method: 'POST',
    body: JSON.stringify({ template_id: templateId, document_ids: documentIds }),
  }, true);
}

export async function getExtractionResults(params?: {
  templateId?: string;
  documentId?: string;
  skip?: number;
  limit?: number;
}): Promise<ExtractionResult[]> {
  const query = new URLSearchParams();
  if (params?.templateId) query.set('template_id', params.templateId);
  if (params?.documentId) query.set('document_id', params.documentId);
  if (params?.skip) query.set('skip', params.skip.toString());
  if (params?.limit) query.set('limit', params.limit.toString());
  const queryStr = query.toString() ? `?${query.toString()}` : '';
  return apiClient.request<ExtractionResult[]>(`/api/v1/extraction/results${queryStr}`, {}, true);
}

export async function getExtractionResult(resultId: string): Promise<ExtractionResult> {
  return apiClient.request<ExtractionResult>(`/api/v1/extraction/results/${resultId}`, {}, true);
}

export async function exportExtractionResults(resultIds: string[], format: ExportFormat): Promise<Blob> {
  const response = await fetch(`${API_BASE_URL}/api/v1/extraction/export`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${localStorage.getItem('accessToken')}`,
    },
    body: JSON.stringify({ result_ids: resultIds, format }),
  });
  if (!response.ok) {
    const error = await response.json().catch(() => ({ detail: 'Export failed' }));
    throw new Error(error.detail || `HTTP ${response.status}`);
  }
  return response.blob();
}

// ============================================================================
// Summarize Types
// ============================================================================

export type SummaryAudience = 'executive' | 'technical' | 'legal' | 'general';
export type SummaryFormat = 'paragraph' | 'bullet' | 'table' | 'timeline' | 'checklist';

export interface SummaryCitation {
  document_id: string;
  document_title?: string;
  chunk_id?: string;
  page_number?: number;
  section?: string;
  text_excerpt: string;
  relevance_score: number;
}

export interface SummarizeRequest {
  document_ids: string[];
  audience: SummaryAudience;
  format: SummaryFormat;
  max_length?: number;
  focus_topics?: string[];
  language?: string;
  include_citations?: boolean;
}

export interface SummaryResult {
  id: string;
  workspace_id: string;
  document_ids: string[];
  document_titles: string[];
  audience: SummaryAudience;
  format: SummaryFormat;
  language: string;
  content: string;
  citations: SummaryCitation[];
  word_count: number;
  focus_topics?: string[];
  created_at: string;
  created_by?: string;
}

// ============================================================================
// Summarize API Functions
// ============================================================================

export async function createSummary(
  workspaceId: string,
  request: SummarizeRequest
): Promise<SummaryResult> {
  return apiClient.request<SummaryResult>(`/api/v1/summarize?workspace_id=${workspaceId}`, {
    method: 'POST',
    body: JSON.stringify(request),
  }, true);
}

export async function getSummaries(
  workspaceId: string,
  params?: {
    documentId?: string;
    audience?: SummaryAudience;
    skip?: number;
    limit?: number;
  }
): Promise<{ summaries: SummaryResult[]; total: number }> {
  const query = new URLSearchParams();
  query.set('workspace_id', workspaceId);
  if (params?.documentId) query.set('document_id', params.documentId);
  if (params?.audience) query.set('audience', params.audience);
  if (params?.skip) query.set('skip', params.skip.toString());
  if (params?.limit) query.set('limit', params.limit.toString());
  return apiClient.request<{ summaries: SummaryResult[]; total: number }>(
    `/api/v1/summarize?${query.toString()}`,
    {},
    true
  );
}

export async function getSummary(summaryId: string, workspaceId: string): Promise<SummaryResult> {
  return apiClient.request<SummaryResult>(
    `/api/v1/summarize/${summaryId}?workspace_id=${workspaceId}`,
    {},
    true
  );
}

export async function deleteSummary(summaryId: string, workspaceId: string): Promise<void> {
  await apiClient.request<void>(
    `/api/v1/summarize/${summaryId}?workspace_id=${workspaceId}`,
    { method: 'DELETE' },
    true
  );
}


// ============================================================================
// Memori Memory Management Types
// ============================================================================

export interface MemoriFact {
  id: number;
  content: string;
  similarity: number;
  lexical_score: number;
  rank_score: number;
}

export interface MemoriTriple {
  subject_name: string;
  subject_type?: string;
  predicate: string;
  object_name: string;
  object_type?: string;
}

export interface MemoriRecallRequest {
  query: string;
  limit?: number;
}

export interface MemoriRecallResponse {
  facts: MemoriFact[];
  query: string;
  total_found: number;
}

export interface MemoriStatsResponse {
  entity_id: string;
  total_facts: number;
  total_triples: number;
  avg_importance: number;
}

// ============================================================================
// Memori Memory Management API Functions
// ============================================================================

/**
 * Recall relevant facts for a query using semantic similarity search.
 */
export async function recallFacts(
  workspaceId: string,
  request: MemoriRecallRequest,
  entityId?: string,
  conversationId?: string
): Promise<MemoriRecallResponse> {
  const query = new URLSearchParams();
  query.set('workspace_id', workspaceId);
  if (entityId) query.set('entity_id', entityId);
  if (conversationId) query.set('conversation_id', conversationId);

  return apiClient.request<MemoriRecallResponse>(
    `/api/v1/memori/recall?${query.toString()}`,
    {
      method: 'POST',
      body: JSON.stringify({
        query: request.query,
        limit: request.limit || 5,
      }),
    },
    true
  );
}

/**
 * Add facts about an entity with embeddings for semantic search.
 */
export async function addFacts(
  entityId: string,
  workspaceId: string,
  facts: { content: string; importance_score?: number }[],
  conversationId?: string
): Promise<number[]> {
  const query = new URLSearchParams();
  query.set('workspace_id', workspaceId);
  if (conversationId) query.set('conversation_id', conversationId);

  return apiClient.request<number[]>(
    `/api/v1/memori/facts/${entityId}?${query.toString()}`,
    {
      method: 'POST',
      body: JSON.stringify(facts),
    },
    true
  );
}

/**
 * Add semantic triples (knowledge graph relationships) for an entity.
 */
export async function addTriples(
  entityId: string,
  workspaceId: string,
  triples: MemoriTriple[],
  conversationId?: string
): Promise<number[]> {
  const query = new URLSearchParams();
  query.set('workspace_id', workspaceId);
  if (conversationId) query.set('conversation_id', conversationId);

  return apiClient.request<number[]>(
    `/api/v1/memori/triples/${entityId}?${query.toString()}`,
    {
      method: 'POST',
      body: JSON.stringify(triples),
    },
    true
  );
}

/**
 * Get knowledge graph (semantic triples) for an entity.
 */
export async function getKnowledgeGraph(
  entityId: string,
  workspaceId: string,
  limit?: number
): Promise<MemoriTriple[]> {
  const query = new URLSearchParams();
  query.set('workspace_id', workspaceId);
  if (limit) query.set('limit', limit.toString());

  return apiClient.request<MemoriTriple[]>(
    `/api/v1/memori/knowledge-graph/${entityId}?${query.toString()}`,
    {},
    true
  );
}

/**
 * Get memory statistics for an entity.
 */
export async function getMemoryStats(
  entityId: string,
  workspaceId: string
): Promise<MemoriStatsResponse> {
  const query = new URLSearchParams();
  query.set('workspace_id', workspaceId);

  return apiClient.request<MemoriStatsResponse>(
    `/api/v1/memori/stats/${entityId}?${query.toString()}`,
    {},
    true
  );
}

/**
 * Cleanup old/low-importance facts to prevent unbounded growth.
 */
export async function cleanupFacts(
  entityId: string,
  workspaceId: string,
  maxFacts?: number,
  minImportance?: number
): Promise<{ deleted_count: number }> {
  const query = new URLSearchParams();
  query.set('workspace_id', workspaceId);
  if (maxFacts) query.set('max_facts', maxFacts.toString());
  if (minImportance) query.set('min_importance', minImportance.toString());

  return apiClient.request<{ deleted_count: number }>(
    `/api/v1/memori/cleanup/${entityId}?${query.toString()}`,
    { method: 'DELETE' },
    true
  );
}
